# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_debug.ipynb.

# %% auto 0
__all__ = ['dpython']

# %% ../nbs/04_debug.ipynb 2
from ._imports import *

# %% ../nbs/04_debug.ipynb 4
@call_parse
def dpython(cmd: Param(type=str)):
    for _ in range(3):
        cmd = cmd.replace('  ', '')
    i_split = cmd.index(".py")+4
    file = cmd[:i_split].strip().split(' ')[1]

    args = cmd[i_split:].split(' ')
    cfg_name = os.environ.get("DNAME", "Latest-Generated")
    cfg = {
        "name": f"Python: {cfg_name}",
        "type": "python",
        "request": "launch",
        "program": f"{file}",
        "console": "integratedTerminal",
        "args": args,
    }
    # pp(cfg)
    mmcv.mkdir_or_exist(".vscode")
    try:
        lauch = mmcv.load(".vscode/launch.json")
    except Exception as e:
        lauch = {
            "version": "0.2.0",
            "configurations": [

            ]
        }
        logger.warning(e)
        
    replace = False
    for i, _cfg in enumerate(lauch['configurations']):
        if _cfg["name"] == cfg["name"]:
            lauch["configurations"][i] = cfg
            replace = True
    if not replace:
        lauch["configurations"] += [cfg]
        mmcv.dump(lauch, '.vscode/launch.json')
